### ISSUE TITLE
malloc():memory corruption(fast)

### ISSUE THREAD

**Issue by Junkai-Liu** [RainerKuemmerle/g2o#308] opened 2018-09-25 12:55 UTC
when i use g2o to optimize sphere.g2o,while running executable file just like below:
./build/pose_graph_g2o_SE3 sphere.g2o                                       output is :
*** Error in `./build/pose_graph_g2o_SE3': malloc(): memory corruption (fast): 0x00000000018d8190 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f50068627e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82651)[0x7f500686d651]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f500686f184]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7f5006e58e78]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs4_Rep9_S_createEmmRKSaIcE+0x59)[0x7f5006e99e39]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs4_Rep8_M_cloneERKSaIcEm+0x1b)[0x7f5006e9ac6b]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs7reserveEm+0x44)[0x7f5006e9ad24]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNKSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE6do_getES3_S3_RSt8ios_baseRSt12_Ios_IostateRd+0x5e)[0x7f5006ed890e]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSi10_M_extractIdEERSiRT_+0x6f)[0x7f5006ec405f]
/usr/local/lib/libg2o_types_slam3d.so(_ZN3g2o7EdgeSE34readERSi+0x305)[0x7f5007454835]
./build/pose_graph_g2o_SE3(main+0x5e0)[0x407150]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f500680b830]
./build/pose_graph_g2o_SE3(_start+0x29)[0x4072b9]
======= Memory map: ========
00400000-0041b000 r-xp 00000000 08:18 1183438                            /home/ghost-knight/slambook/ch11/build/pose_graph_g2o_SE3
0061a000-0061b000 r--p 0001a000 08:18 1183438                            /home/ghost-knight/slambook/ch11/build/pose_graph_g2o_SE3
0061b000-0061c000 rw-p 0001b000 08:18 1183438                            /home/ghost-knight/slambook/ch11/build/pose_graph_g2o_SE3
017af000-018f9000 rw-p 00000000 00:00 0                                  [heap]
7f4ffc000000-7f4ffc021000 rw-p 00000000 00:00 0 
7f4ffc021000-7f5000000000 ---p 00000000 00:00 0 
7f500159b000-7f50015d9000 r-xp 00000000 08:14 3539380                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7f50015d9000-7f50017d8000 ---p 0003e000 08:14 3539380                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7f50017d8000-7f50017d9000 r--p 0003d000 08:14 3539380                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7f50017d9000-7f50017da000 rw-p 0003e000 08:14 3539380                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7f50017da000-7f50017df000 r-xp 00000000 08:14 3548172                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f50017df000-7f50019de000 ---p 00005000 08:14 3548172                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f50019de000-7f50019df000 r--p 00004000 08:14 3548172                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f50019df000-7f50019e0000 rw-p 00005000 08:14 3548172                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f50019e0000-7f50019e2000 r-xp 00000000 08:14 3548161                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f50019e2000-7f5001be2000 ---p 00002000 08:14 3548161                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f5001be2000-7f5001be3000 r--p 00002000 08:14 3548161                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f5001be3000-7f5001be4000 rw-p 00003000 08:14 3548161                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f5001be4000-7f5001d0d000 r-xp 00000000 08:14 3542210                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7f5001d0d000-7f5001f0c000 ---p 00129000 08:14 3542210                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7f5001f0c000-7f5001f0d000 r--p 00128000 08:14 3542210                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7f5001f0d000-7f5001f0f000 rw-p 00129000 08:14 3542210                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7f5001f0f000-7f5001f12000 r-xp 00000000 08:14 530574                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f5001f12000-7f5002111000 ---p 00003000 08:14 530574                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f5002111000-7f5002112000 r--p 00002000 08:14 530574                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f5002112000-7f5002113000 rw-p 00003000 08:14 530574                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f5002113000-7f5002123000 r-xp 00000000 08:14 3543741                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f5002123000-7f5002323000 ---p 00010000 08:14 3543741                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f5002323000-7f5002324000 r--p 00010000 08:14 3543741                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f5002324000-7f5002325000 rw-p 00011000 08:14 3543741                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f5002325000-7f500232a000 r-xp 00000000 08:14 3548212                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f500232a000-7f5002529000 ---p 00005000 08:14 3548212                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f5002529000-7f500252a000 r--p 00004000 08:14 3548212                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f500252a000-7f500252b000 rw-p 00005000 08:14 3548212                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f500252b000-7f500254c000 r-xp 00000000 08:14 3549579                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f500254c000-7f500274b000 ---p 00021000 08:14 3549579                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f500274b000-7f500274c000 r--p 00020000 08:14 3549579                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f500274c000-7f500274d000 rw-p 00021000 08:14 3549579                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f500274d000-7f5002751000 r-xp 00000000 08:14 3549547                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f5002751000-7f5002950000 ---p 00004000 08:14 3549547                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f5002950000-7f5002951000 r--p 00003000 08:14 3549547                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f5002951000-7f5002952000 rw-p 00004000 08:14 3549547                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f5002952000-7f5002969000 r-xp 00000000 08:14 3549551                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f5002969000-7f5002b68000 ---p 00017000 08:14 3549551                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f5002b68000-7f5002b6a000 r--p 00016000 08:14 3549551                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f5002b6a000-7f5002b6b000 rw-p 00018000 08:14 3549551                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f5002b6b000-7f5002ca0000 r-xp 00000000 08:14 3541510                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f5002ca0000-7f5002ea0000 ---p 00135000 08:14 3541510                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f5002ea0000-7f5002ea1000 r--p 00135000 08:14 3541510                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f5002ea1000-7f5002ea5000 rw-p 00136000 08:14 3541510                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f5002ea5000-7f5002ea6000 r-xp 00000000 08:14 3541515                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f5002ea6000-7f50030a5000 ---p 00001000 08:14 3541515                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f50030a5000-7f50030a6000 r--p 00000000 08:14 3541515                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f50030a6000-7f50030a7000 rw-p 00001000 08:14 3541515                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f50030a7000-7f50030ac000 r-xp 00000000 08:14 3548176                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f50030ac000-7f50032ab000 ---p 00005000 08:14 3548176                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f50032ab000-7f50032ac000 r--p 00004000 08:14 3548176                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f50032ac000-7f50032ad000 rw-p 00005000 08:14 3548176                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f50032ad000-7f50032af000 r-xp 00000000 08:14 3548170                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f50032af000-7f50034ae000 ---p 00002000 08:14 3548170                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f50034ae000-7f50034af000 r--p 00001000 08:14 3548170                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f50034af000-7f50034b0000 rw-p 00002000 08:14 3548170                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f50034b0000-7f50034c1000 r-xp 00000000 08:14 3548174                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f50034c1000-7f50036c0000 ---p 00011000 08:14 3548174                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f50036c0000-7f50036c1000 r--p 00010000 08:14 3548174                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f50036c1000-7f50036c2000 rw-p 00011000 08:14 3548174                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f50036c2000-7f50036ee000 r-xp 00000000 08:14 3546129                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f50036ee000-7f50038ed000 ---p 0002c000 08:14 3546129                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f50038ed000-7f50038f1000 r--p 0002b000 08:14 3546129                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f50038f1000-7f50038f2000 rw-p 0002f000 08:14 3546129                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f50038f2000-7f50038f3000 rw-p 00000000 00:00 0 
7f50038f3000-7f50038f4000 r-xp 00000000 08:14 3549591                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f50038f4000-7f5003af4000 ---p 00001000 08:14 3549591                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f5003af4000-7f5003af5000 r--p 00001000 08:14 3549591                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f5003af5000-7f5003af6000 rw-p 00002000 08:14 3549591                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f5003af6000-7f5003afb000 r-xp 00000000 08:14 3549571                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f5003afb000-7f5003cfb000 ---p 00005000 08:14 3549571                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f5003cfb000-7f5003cfc000 r--p 00005000 08:14 3549571                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f5003cfc000-7f5003cfd000 rw-p 00006000 08:14 3549571                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f5003cfd000-7f5003cff000 r-xp 00000000 08:14 3549559                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f5003cff000-7f5003efe000 ---p 00002000 08:14 3549559                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f5003efe000-7f5003eff000 r--p 00001000 08:14 3549559                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f5003eff000-7f5003f00000 rw-p 00002000 08:14 3549559                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f5003f00000-7f5003f02000 r-xp 00000000 08:14 3549549                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f5003f02000-7f5004101000 ---p 00002000 08:14 3549549                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f5004101000-7f5004102000 r--p 00001000 08:14 3549549                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f5004102000-7f5004103000 rw-p 00002000 08:14 3549549                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f5004103000-7f5004129000 r-xp 00000000 08:14 529139                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f5004129000-7f5004329000 ---p 00026000 08:14 529139                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f5004329000-7f500432b000 r--p 00026000 08:14 529139                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f500432b000-7f500432c000 rw-p 00028000 08:14 529139                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f500432c000-7f5004345000 r-xp 00000000 08:14 529299                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f5004345000-7f5004544000 ---p 00019000 08:14 529299                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f5004544000-7f5004545000 r--p 00018000 08:14 529299                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f5004545000-7f5004546000 rw-p 00019000 08:14 529299                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f5004546000-7f50045b3000 r-xp 00000000 08:14 3548017                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f50045b3000-7f50047b3000 ---p 0006d000 08:14 3548017                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f50047b3000-7f50047b4000 r--p 0006d000 08:14 3548017                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f50047b4000-7f50047b5000 rw-p 0006e000 08:14 3548017                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f50047b5000-7f50047cd000 r-xp 00000000 08:14 530571                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f50047cd000-7f50049cc000 ---p 00018000 08:14 530571                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f50049cc000-7f50049cd000 r--p 00017000 08:14 530571                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f50049cd000-7f50049ce000 rw-p 00018000 08:14 530571                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f50049ce000-7f50049d2000 rw-p 00000000 00:00 0 
7f50049d2000-7f50049d4000 r-xp 00000000 08:14 3549331                    /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7f50049d4000-7f5004bd3000 ---p 00002000 08:14 3549331                    /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7f5004bd3000-7f5004bd4000 r--p 00001000 08:14 3549331                    /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7f5004bd4000-7f5004bd5000 rw-p 00002000 08:14 3549331                    /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7f5004bd5000-7f5004bde000 r-xp 00000000 08:14 3562087                    /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7f5004bde000-7f5004dde000 ---p 00009000 08:14 3562087                    /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7f5004dde000-7f5004ddf000 r--p 00009000 08:14 3562087                    /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7f5004ddf000-7f5004de0000 rw-p 0000a000 08:14 3562087                    /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7f5004de0000-7f5004de9000 r-xp 00000000 08:14 3562086                    /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7f5004de9000-7f5004fe8000 ---p 00009000 08:14 3562086                    /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7f5004fe8000-7f5004fe9000 r--p 00008000 08:14 3562086                    /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7f5004fe9000-7f5004fea000 rw-p 00009000 08:14 3562086                    /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7f5004fea000-7f5004ff0000 r-xp 00000000 08:14 3548386                    /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7f5004ff0000-7f50051ef000 ---p 00006000 08:14 3548386                    /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7f50051ef000-7f50051f0000 r--p 00005000 08:14 3548386                    /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7f50051f0000-7f50051f1000 rw-p 00006000 08:14 3548386                    /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7f50051f1000-7f50051f9000 r-xp 00000000 08:14 3562080                    /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7f50051f9000-7f50053f8000 ---p 00008000 08:14 3562080                    /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7f50053f8000-7f50053f9000 r--p 00007000 08:14 3562080                    /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7f50053f9000-7f50053fa000 rw-p 00008000 08:14 3562080                    /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7f50053fa000-7f50059ee000 r-xp 00000000 08:14 2230614                    /usr/lib/lapack/liblapack.so.3.6.0
7f50059ee000-7f5005bed000 ---p 005f4000 08:14 2230614                    /usr/lib/lapack/liblapack.so.3.6.0
7f5005bed000-7f5005bee000 r--p 005f3000 08:14 2230614                    /usr/lib/lapack/liblapack.so.3.6.0
7f5005bee000-7f5005bf2000 rw-p 005f4000 08:14 2230614                    /usr/lib/lapack/liblapack.so.3.6.0
7f5005bf2000-7f5005c60000 r-xp 00000000 08:14 2230575                    /usr/lib/libblas/libblas.so.3.6.0
7f5005c60000-7f5005e5f000 ---p 0006e000 08:14 2230575                    /usr/lib/libblas/libblas.so.3.6.0
7f5005e5f000-7f5005e60000 r--p 0006d000 08:14 2230575                    /usr/lib/libblas/libblas.so.3.6.0
7f5005e60000-7f5005e61000 rw-p 0006e000 08:14 2230575                    /usr/lib/libblas/libblas.so.3.6.0
7f5005e61000-7f5005ed1000 r-xp 00000000 08:14 3801714                    /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
7f5005ed1000-7f50060d0000 ---p 00070000 08:14 3801714                    /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
7f50060d0000-7f50060d3000 r--p 0006f000 08:14 3801714                    /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
7f50060d3000-7f50060d4000 rw-p 00072000 08:14 3801714                    /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
7f50060d4000-7f50060d5000 rw-p 00000000 00:00 0 
7f50060d5000-7f50060d8000 r-xp 00000000 08:14 3551590                    /usr/local/lib/libg2o_opengl_helper.so
7f50060d8000-7f50062d8000 ---p 00003000 08:14 3551590                    /usr/local/lib/libg2o_opengl_helper.so
7f50062d8000-7f50062d9000 r--p 00003000 08:14 3551590                    /usr/local/lib/libg2o_opengl_helper.so
7f50062d9000-7f50062da000 rw-p 00004000 08:14 3551590                    /usr/local/lib/libg2o_opengl_helper.so
7f50062da000-7f50062e1000 r-xp 00000000 08:14 530590                     /lib/x86_64-linux-gnu/librt-2.23.so
7f50062e1000-7f50064e0000 ---p 00007000 08:14 530590                     /lib/x86_64-linux-gnu/librt-2.23.so
7f50064e0000-7f50064e1000 r--p 00006000 08:14 530590                     /lib/x86_64-linux-gnu/librt-2.23.so
7f50064e1000-7f50064e2000 rw-p 00007000 08:14 530590                     /lib/x86_64-linux-gnu/librt-2.23.so
7f50064e2000-7f50065ea000 r-xp 00000000 08:14 530568                     /lib/x86_64-linux-gnu/libm-2.23.so
7f50065ea000-7f50067e9000 ---p 00108000 08:14 530568                     /lib/x86_64-linux-gnu/libm-2.23.so
7f50067e9000-7f50067ea000 r--p 00107000 08:14 530568                     /lib/x86_64-linux-gnu/libm-2.23.so
7f50067ea000-7f50067eb000 rw-p 00108000 08:14 530568                     /lib/x86_64-linux-gnu/libm-2.23.so
7f50067eb000-7f50069ab000 r-xp 00000000 08:14 530572                     /lib/x86_64-linux-gnu/libc-2.23.so
7f50069ab000-7f5006bab000 ---p 001c0000 08:14 530572                     /lib/x86_64-linux-gnu/libc-2.23.so
7f5006bab000-7f5006baf000 r--p 001c0000 08:14 530572                     /lib/x86_64-linux-gnu/libc-2.23.so
7f5006baf000-7f5006bb1000 rw-p 001c4000 08:14 530572                     /lib/x86_64-linux-gnuAborted (core dumped)

how to fix this problem ,mine operating system is Ubuntu16.04LTS

**Comment by RainerKuemmerle** [comment] 2019-04-07 07:09
Duplicate of #315

**Closed by RainerKuemmerle** 2019-04-07 07:09 UTC
