### ISSUE TITLE
EdgeSe3  jacobian

### ISSUE THREAD

**Issue by lianbin** [RainerKuemmerle/g2o#474] opened 2021-01-03 08:40 UTC
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/types/slam3d/isometry3d_gradients.h#L194
Can anyone tell me how the Jacobi here is derived? Or related reference papers

**Comment by RainerKuemmerle** [comment] 2021-01-03 10:46
Duplicate of #146

**Closed by RainerKuemmerle** 2021-01-03 10:46 UTC
